const API="/.netlify/functions/dictionary";
let DATA=[],password="",deleteId=null;
const $=s=>document.querySelector(s);const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const fields=["headword","type","lexicalField","microfield","modernMeaning","context","book","firstPage","pages","classificationBasis","confidence","note"];
async function fetchData(){try{const r=await fetch(API,{cache:"no-store"});if(r.ok){const v=await r.json();if(Array.isArray(v)&&v.length)return v}}catch{}const r=await fetch("data.json",{cache:"no-store"});return r.json()}
async function persist(next){const r=await fetch(API,{method:"PUT",headers:{"content-type":"application/json","x-admin-password":password},body:JSON.stringify(next)});const v=await r.json();if(!r.ok)throw new Error(v.error||"Saqlanmadi.");DATA=next;render()}
function render(){const q=$("#search").value.trim().toLocaleLowerCase("uz");const rows=DATA.filter(x=>!q||`${x.headword} ${x.type} ${x.lexicalField} ${x.modernMeaning}`.toLocaleLowerCase("uz").includes(q));$("#total").textContent=DATA.length;$("#hist").textContent=DATA.filter(x=>x.type==="Istorizm").length;$("#arch").textContent=DATA.filter(x=>x.type==="Arxaizm").length;$("#rows").innerHTML=rows.map(x=>`<tr><td>${x.id}</td><td>${esc(x.headword)}</td><td>${esc(x.type)}</td><td>${esc(x.lexicalField)}</td><td>${esc(x.modernMeaning)}</td><td>${esc(x.firstPage)}</td><td><div class="actions"><button data-edit="${x.id}">Tahrirlash</button><button class="remove" data-delete="${x.id}">O‘chirish</button></div></td></tr>`).join("");$("#cards").innerHTML=rows.map(x=>`<article class="admin-card"><h3>${esc(x.headword)}</h3><small>${esc(x.type)} · № ${x.id}</small><p>${esc(x.modernMeaning)}</p><div class="actions"><button data-edit="${x.id}">Tahrirlash</button><button class="remove" data-delete="${x.id}">O‘chirish</button></div></article>`).join("")}
function openEditor(item=null){$("#formTitle").textContent=item?"So‘zni tahrirlash":"Yangi so‘z qo‘shish";$("#wordId").value=item?.id??"";for(const name of fields)$("#"+name).value=item?.[name]??({type:"Istorizm",book:1,firstPage:1,confidence:"Yuqori"}[name]??"");$("#formError").textContent="";$("#editor").showModal()}
function clickList(e){const edit=e.target.closest("[data-edit]");const del=e.target.closest("[data-delete]");if(edit)openEditor(DATA.find(x=>x.id===Number(edit.dataset.edit)));if(del){deleteId=Number(del.dataset.delete);const item=DATA.find(x=>x.id===deleteId);$("#confirmText").textContent=`“${item?.headword}” lug‘atdan butunlay olib tashlanadi.`;$("#confirm").showModal()}}
$("#loginForm").addEventListener("submit",async e=>{e.preventDefault();password=$("#password").value;$("#loginError").textContent="";try{DATA=await fetchData();const test=await fetch(API,{method:"PUT",headers:{"content-type":"application/json","x-admin-password":password},body:JSON.stringify(DATA)});const v=await test.json();if(!test.ok)throw new Error(v.error||"Kirish amalga oshmadi.");sessionStorage.setItem("adminUnlocked","1");$("#login").hidden=true;$("#panel").hidden=false;render()}catch(err){$("#loginError").textContent=err.message}});
$("#wordForm").addEventListener("submit",async e=>{e.preventDefault();const button=$("#save");button.disabled=true;$("#formError").textContent="";try{const id=Number($("#wordId").value)||Math.max(0,...DATA.map(x=>Number(x.id)))+1;const item={id};for(const name of fields)item[name]=["book","firstPage"].includes(name)?Number($("#"+name).value):$("#"+name).value.trim();const exists=DATA.some(x=>x.id===id);const next=exists?DATA.map(x=>x.id===id?item:x):[...DATA,item];await persist(next);$("#editor").close();showNotice(exists?"So‘z yangilandi.":"Yangi so‘z qo‘shildi.")}catch(err){$("#formError").textContent=err.message}finally{button.disabled=false}});
$("#delete").addEventListener("click",async()=>{const button=$("#delete");button.disabled=true;try{await persist(DATA.filter(x=>x.id!==deleteId));$("#confirm").close();showNotice("So‘z o‘chirildi.")}catch(err){alert(err.message)}finally{button.disabled=false}});
function showNotice(text){$("#notice").textContent=text;setTimeout(()=>$("#notice").textContent="",3000)}
$("#search").addEventListener("input",render);$("#rows").addEventListener("click",clickList);$("#cards").addEventListener("click",clickList);$("#add").addEventListener("click",()=>openEditor());$("#closeEditor").addEventListener("click",()=>$("#editor").close());$("#cancel").addEventListener("click",()=>$("#editor").close());$("#cancelDelete").addEventListener("click",()=>$("#confirm").close());$("#logout").addEventListener("click",()=>{sessionStorage.clear();location.reload()});
